### ISSUE TITLE
Receipies of C#

### ISSUE THREAD

**Issue by parthopdas** [InnovatingTeams/provable-refactorings#15]
Hi friends, hope you are doing well.

I was think of adding ones corresponding to C#. Before that though can you please tell me why we cannot take advantage of the refactorings provided by the IDE or tools like R#?

Or are these things only for cpp where the refactoring tools aren't powerful enough?

Thanks, 
Partho

**Comment by JayBazuzi** [comment]
Hey Partho!

For most cases, use the ReSharper refactorings. 

The relationship between good refactoring tools and these recipes is that the tools are a program that carries out the recipe: they're basically the same thing. So if you have a good tool, use it.

Sometimes you want a refactoring that is missing in your tools, or the refactoring tool is unable to correctly handle your specific case. Then, use a manual recipe.

**Comment by arlobelshee** [comment]
Good to hear from you again Partho!

What Jay said. Also, there are some refactorings that aren't in R#, aren't in VStudio, or the tool implementations are buggy. Those would be good ones for recipes.

**Comment by parthopdas** [comment]
Thank you guys. This is a great initiative.

PS: Most of my core dev skills are thanks to you. Hope to work with you again sometime in the future.

Closing this issue.
